set nocompatible
set backspace=indent,eol,start

set relativenumber
set number
syntax on
set autoindent
set nosmartindent
filetype indent on
set noexpandtab
set modeline
set hlsearch
set wrap linebreak breakindent

" set colorcolumn=81

au BufRead,BufNewFile *.vue set filetype=vue
autocmd Filetype html,vue setlocal syntax=html ts=2 softtabstop=2 shiftwidth=2 expandtab colorcolumn=9999
autocmd Filetype php setlocal ts=4 softtabstop=4 shiftwidth=4 expandtab
autocmd Filetype python setlocal ts=4 softtabstop=0 shiftwidth=4 noexpandtab
autocmd Filetype javascript setlocal ts=2 softtabstop=2 shiftwidth=2 expandtab
autocmd Filetype yaml setlocal ts=2 softtabstop=2 shiftwidth=2 expandtab

set tags+=~/.vim/tags/opengl
set tags+=**
set wildignore+=**/node_modules
set wildignore+=vendor
set wildignore+=build

" Open definition of function
map <F5> <C-w><C-]><C-w>T

" Open new file
map <F6> :tabm -1<CR>
map <F7> :tabp<CR>
map <F8> :tabf 
map <F9> :tabn<CR>
map <F10> :tabm +1<CR>

" Goto file in new tab
nnoremap gf <C-W>gf
vnoremap gf <C-W>gf

" Additional symbols
map =e a∈<ESC>
map =/e a∉<ESC>
map =c a⊂<ESC>
map =/c a⊄<ESC>
map =u a∪<ESC>
map =/u a∩<ESC>
map =! a∁<ESC>
map =I a∫<ESC>
map =S a∑<ESC>
map == a≡<ESC>
map =D aΔ<ESC>
map =P aπ<ESC>
map =R aρ<ESC>

" Use ctrl-[hjkl] to select the active split!
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

" Close quickfix
" nmap <c-q> :ccl<CR>

" Add closing bracket when opening bracket is typed
" inoremap ( ()<Left>
" inoremap { {}<Left>

" Folds
set foldmethod=indent
set nofoldenable
vnoremap <Space> zf

" set mouse=a
" set ballooneval
" set balloonevalterm
" if has("mouse_sgr")
"     set ttymouse=sgr
" else
"     set ttymouse=xterm2
" end
set mousemoveevent

set path=.,**,
set wildignore+=**/node_modules/**

command Ctags !ctags -R

" Syntastic config
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*
" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0
" let g:syntastic_javascript_checkers = ['eslint']
" let g:ale_enabled = 1
let g:ale_completion_enabled = 1
let g:ale_set_balloons = 1
let g:ale_hover_cursor = 1
let g:ale_linters = {'c': ['ccls'], 'go': ['gofmt', 'golint', 'govet', 'gopls'], 'python': ['python-language-server', 'pyls'], 'php': ['phpactor'], 'vue': ['volar']}
let g:ale_python_flake8_options = "--ignore=E501,E302,E225,E201,E303,E722,E265,E116,F405,W191,W391"
let g:ale_completion_autoimport = 1
let g:ale_virtualtext_cursor = 2
" let g:ale_virtualtext_cursor = 'disabled'
let g:ale_floating_preview = 1
" let g:ale_hover_to_preview = 0
" let g:ale_detail_to_floating_preview = 1
" let g:ale_cursor_detail = 1
let g:ale_popup_menu_enabled = 1
" nmap gd :ALEGoToDefinition<Space>-tab<CR>
map <PageUp> :labove<CR>
map <PageDown> :lbelow<CR>
" nnoremenu PopUp.RenameSymbol :ALERename<CR> " Add rename option to right-click menu

" Open NERDTree with tab
map <Tab> :NERDTreeToggle<CR>
let NERDTreeCustomOpenArgs={'file':{'where': 't'}}

" Control-T config
let g:CommandTPreferredImplementation='lua'
let g:CommandTEncoding='utf-8'
let g:CommandTWildIgnore='node_modules'
map <C-t> :CommandT<CR>

" Ack config
let g:ack_default_options = " -s -H --nopager --nocolor --nogroup --column"
map <C-f> :Ack!<Space>

execute pathogen#infect()

call plug#begin()

" List your plugins here
Plug 'williamboman/mason.nvim'
Plug 'williamboman/mason-lspconfig.nvim'
Plug 'neovim/nvim-lspconfig'

call plug#end()

source ~/.vim/nvimrc.lua

